// ── Alice Syllabus Data ─────────────────────────────────────────────────────
// Data yahan update karein. Future mein Django API se replace hoga.

// Color cycling array - Alice dark theme accents
export const BLOCK_COLORS = [
  { bg: 'rgba(63,185,80,0.1)',   border: 'rgba(63,185,80,0.4)',   accent: '#3fb950' },
  { bg: 'rgba(121,192,255,0.1)', border: 'rgba(121,192,255,0.4)', accent: '#79c0ff' },
  { bg: 'rgba(210,153,34,0.1)',  border: 'rgba(210,153,34,0.4)',  accent: '#e3b341' },
  { bg: 'rgba(248,81,73,0.1)',   border: 'rgba(248,81,73,0.4)',   accent: '#f85149' },
  { bg: 'rgba(163,113,247,0.1)', border: 'rgba(163,113,247,0.4)', accent: '#a371f7' },
]

export const syllabusData = {

  // ══════════════════════════════════════════════
  //  FIRST YEAR
  // ══════════════════════════════════════════════
  'first-year': {
    label: 'First Year',
    semesters: {
      1: {
        label: 'Semester 1',
        subjects: [
          { id: 'bt101', name: 'BT-101 - Engineering Chemistry', units: [
            { unit: 1, title: 'Water – Analysis, Treatments and Industrial Applications', content: 'Sources, Impurities, Hardness & its units, Determination of hardness by EDTA method, Alkalinity & Its determination and related numerical problems.' },
            { unit: 2, title: 'Boiler Problem & Softening Methods', content: 'Boiler troubles (Sludge & Scale, Priming & Foaming, Boiler Corrosion, Caustic Embrittlement), Softening methods (Lime-Soda, Zeolite and Ion Exchange Methods) and related numerical problems.' },
            { unit: 3, title: 'Lubricants and Lubrication', content: 'Introduction, Mechanism of lubrication, Classification of lubricants, significance & determination of Viscosity and Viscosity Index, Flash & Fire Points, Cloud & Pour Points, Aniline Point, Acid Number, Saponification Number, Steam Emulsification Number and related numerical problems.' },
            { unit: 4, title: 'Polymer & Polymerization', content: 'Introduction, types of polymerisation, Classification, mechanism of polymerisation (Free radical & Ionic polymerization). Thermoplastic & Thermosetting polymers. Elementary idea of Biodegradable polymers, preparation, properties & uses of the following polymers: PVC, PMMA, Teflon, Nylon 6, Nylon 6:6, Polyester, Phenol Formaldehyde, Urea-Formaldehyde, Buna N, Buna S, Vulcanization of Rubber.' },
            { unit: 5, title: 'Phase Equilibrium and Corrosion', content: 'Phase diagram of single component system (Water). Phase diagram of binary Eutectic System (Cu-Ag). Corrosion: Types, Mechanisms & Prevention.' },
            { unit: 6, title: 'Spectroscopic Techniques and Application', content: 'Principle, Instrumentation & Applications, Electronics Spectroscopy, Vibrational & Rotational Spectroscopy of diatomic molecules.' },
            { unit: 7, title: 'Periodic Properties', content: 'Effective Nuclear Charge, Variations: S, P, d & f Orbital energies of atoms in periodic table, Electronics Configuration, Atomic & Ionic sizes, Electron Affinity & Electronegativity, Polarizability & Oxidation States.' },
          ] },
          { id: 'bt102', name: 'BT-102 - Mathematics-I', units: [
            { unit: 1, title: 'Calculus – Differentiation', content: 'Rolle\'s theorem, Mean Value theorems, Expansion of functions by McLaurin\'s and Taylor\'s for one variable; Taylor\'s theorem for function of two variables, Partial Differentiation, Maxima & Minima (two and three variables), Method of Lagranges Multipliers. (10 hours)' },
            { unit: 2, title: 'Calculus – Integration', content: 'Definite Integral as a limit of a sum and its application in summation of series; Beta and Gamma functions and their properties; Applications of definite integrals to evaluate surface areas and volumes of revolutions. Multiple Integral, Change the order of the integration, Applications of multiple integral for calculating area and volumes of the curves. (8 hours)' },
            { unit: 3, title: 'Sequences and Series', content: 'Convergence of sequence and series, tests for convergence; Power series, Taylor\'s series, series for exponential, trigonometric and logarithm functions; Fourier series: Half range sine and cosine series, Parseval\'s theorem. (6 hours)' },
            { unit: 4, title: 'Vector Spaces', content: 'Vector Space, Vector Sub Space, Linear Combination of Vectors, Linearly Dependent, Linearly Independent, Basis of a Vector Space, Linear Transformations. (8 hours)' },
            { unit: 5, title: 'Matrices', content: 'Rank of a Matrix, Solution of Simultaneous Linear Equations by Elementary Transformation, Consistency of Equation, Eigen Values and Eigen Vectors, Diagonalization of Matrices, Cayley-Hamilton theorem and its applications to find inverse. (8 hours)' },
          ] },
          { id: 'bt103', name: 'BT-103 - English for Communication', units: [
            { unit: 1, title: 'Identifying Common Errors in Writing', content: 'Articles, Subject-Verb Agreement, Prepositions, Active and Passive Voice, Reported Speech: Direct and Indirect, Sentence Structure.' },
            { unit: 2, title: 'Vocabulary Building and Comprehension', content: 'Acquaintance with prefixes and suffixes from foreign languages in English to form derivatives, synonyms, antonyms, Reading comprehension.' },
            { unit: 3, title: 'Communication', content: 'Introduction, Meaning and Significance, Process of Communication, Oral and Written Communication, 7 C\'s of Communication, Barriers to Communication and Ways to overcome them, Importance of Communication for Technical students, Nonverbal Communication.' },
            { unit: 4, title: 'Developing Writing Skills', content: 'Planning, Drafting and Editing, Precise Writing, Précis, Technical definition and Technical description. Report Writing: Features of writing a good Report, Structure of a Formal Report, Report of Trouble, Laboratory Report, Progress Report.' },
            { unit: 5, title: 'Business Correspondence', content: 'Importance of Business Letters, Parts and Layout; Application, Contents of good Resume, guidelines for writing Resume, Calling/Sending Quotation, Order, Complaint, E-mail and Tender.' },
          ] },
          { id: 'bt104', name: 'BT-104 - Basic Electrical & Electronics Engineering', units: [
            { unit: 1, title: 'D.C. Circuits', content: 'Voltage and current sources, dependent and independent sources, Units and dimensions, Source Conversion, Ohm\'s Law, Kirchhoff\'s Law, Superposition theorem, Thevenin\'s theorem and their application for analysis of series and parallel resistive circuits excited by independent voltage sources, Power & Energy in such circuits. Mesh & nodal analysis, Star Delta transformation & circuits.' },
            { unit: 2, title: '1-Phase & 3-Phase AC Circuits', content: '1-Phase: Generation of sinusoidal AC voltage, definition of average value, R.M.S. value, form factor and peak factor of AC quantity, Concept of phasor, Power factor, impedance and admittance, Active, reactive and apparent power, analysis of R-L, R-C, R-L-C series & parallel circuits. 3-Phase: Necessity and advantages, Meaning of Phase sequence, balanced and unbalanced supply and loads. Relationship between line and phase values for balanced star and delta connections. Power in balanced & unbalanced three-phase system and their measurements.' },
            { unit: 3, title: 'Magnetic Circuits & Single Phase Transformer', content: 'Basic definitions, magnetization characteristics of Ferro magnetic materials, self inductance and mutual inductance, energy in linear magnetic systems, coils connected in series, AC excitation in magnetic circuits, magnetic field produced by current carrying conductor, Force on a current carrying conductor. Induced voltage, laws of electromagnetic Induction, direction of induced E.M.F. Single phase transformer: General construction, working principle, e.m.f. equation, equivalent circuits, phasor diagram, voltage regulation, losses and efficiency, open circuit and short circuit test.' },
            { unit: 4, title: 'Electrical Machines', content: 'Construction, Classification & Working Principle of DC machine, induction machine and synchronous machine. Working principle of 3-Phase induction motor, Concept of slip, Explanation of Torque-slip characteristics. Types of losses occurring in electrical machines. Applications of DC machine, induction machine and synchronous machine.' },
            { unit: 5, title: 'Basic Electronics', content: 'Number systems & Their conversion used in digital electronics, De Morgan\'s theorem, Logic Gates, half and full adder circuits, R-S flip flop, J-K flip flop. Introduction to Semiconductors, Diodes, V-I characteristics, Bipolar junction transistors (BJT) and their working, introduction to CC, CB & CE transistor configurations, different configurations and modes of operation of BJT.' },
          ] },
          { id: 'bt105', name: 'BT-105 - Engineering Graphics', units: [
            { unit: 1, title: 'Introduction to Engineering Drawing', content: 'Principles of Engineering Graphics and their significance, usage of Drawing instruments, lettering, Conic sections including the Rectangular Hyperbola (General method only); Cycloid, Epicycloid, Hypocycloid and Involute; Scales – Plain, Diagonal and Vernier Scales.' },
            { unit: 2, title: 'Orthographic Projections', content: 'Principles of Orthographic Projections – Conventions; Projections of Points and lines inclined to both planes; Projections of planes inclined Planes – Auxiliary Planes.' },
            { unit: 3, title: 'Projections of Regular Solids', content: 'Projections of Regular Solids inclined to both the Planes – Auxiliary Views; Draw simple annotation, dimensioning and scale. Floor plans that include: windows, doors, and fixtures such as WC, bath, sink, shower, etc.' },
            { unit: 4, title: 'Sections, Sectional Views & Surface Development', content: 'Sections and Sectional Views of Right Angular Solids: Prism, Cylinder, Pyramid, Cone – Auxiliary Views; Development of surfaces of Right Regular Solids – Prism, Pyramid, Cylinder and Cone; Draw the sectional orthographic views of geometrical solids, objects from industry and dwellings (foundation to slab only).' },
            { unit: 5, title: 'Isometric Projections', content: 'Principles of Isometric projection – Isometric Scale, Isometric Views, Conventions; Isometric Views of lines, Planes, Simple and compound Solids; Conversion of Isometric Views to Orthographic Views and Vice-versa, Conventions.' },
            { unit: 6, title: 'Overview of Computer Graphics', content: 'Listing the computer technologies that impact on graphical communication, Demonstrating knowledge of the theory of CAD software: The Menu System, Toolbars (Standard, Object Properties, Draw, Modify and Dimension), Drawing Area (Background, Crosshairs, Coordinate System), Dialog boxes, Shortcut menus, The Command Line, The Status Bar, Different methods of zoom as used in CAD, Select and erase objects; Isometric Views of lines, Planes, Simple and compound Solids.' },
            { unit: 7, title: 'Customisation & CAD Drawing', content: 'Set up of the drawing page and the printer, including scale settings; Setting up of units and drawing limits; ISO and ANSI standards for coordinate dimensioning and tolerancing; Orthographic constraints, Snap to objects manually and automatically; Producing drawings by using various coordinate input entry methods to draw straight lines; Applying various ways of drawing circles.' },
            { unit: 8, title: 'Annotations, Layering & Other Functions', content: 'Applying dimensions to objects, applying annotations to drawings; Setting up and use of Layers to create drawings; Create, edit and use customized layers; Changing line lengths through modifying existing lines (extend/lengthen); Printing documents using the print command; Orthographic projection techniques; Drawing sectional views of composite right regular geometric solids; Parametric and non-parametric solid, surface, and wireframe models; Dimensioning guidelines, tolerancing techniques; dimensioning and scale multi views of dwelling.' },
            { unit: 9, title: 'Team Design Project & BIM Introduction', content: 'Demonstration of a simple team design project illustrating Geometry and topology of engineered components: creation of engineering models in standard 2D blueprint form and as 3D wire-frame and shaded solids; meshed topologies for engineering analysis and toolpath generation; geometric dimensioning and tolerancing; Use of solid modeling software for creating associative models at the component and assembly levels; floor plans including windows, doors, and fixtures; Applying colour coding according to building drawing practice; Drawing sectional elevation showing foundation to ceiling; Introduction to Building Information Modelling (BIM).' },
          ] },
          { id: 'bt106', name: 'BT-106 - Manufacturing Practices', units: [
            { unit: 1, title: 'Manufacturing Methods', content: 'Overview of manufacturing methods: casting, forming, machining, joining, and advanced manufacturing methods. (3 lectures)' },
            { unit: 2, title: 'CNC Machining & Additive Manufacturing', content: 'Introduction to CNC machining processes and Additive manufacturing (3D printing) techniques and their industrial applications. (1 lecture)' },
            { unit: 3, title: 'Fitting Operations & Power Tools', content: 'Bench work and fitting operations; use of hand tools and power tools in manufacturing and assembly. (1 lecture)' },
            { unit: 4, title: 'Electrical & Electronics', content: 'Basic electrical and electronics practices in a manufacturing context, including components, wiring, and safety. (1 lecture)' },
            { unit: 5, title: 'Carpentry', content: 'Wood-working tools, joints, and carpentry practices used in manufacturing and construction. (1 lecture)' },
            { unit: 6, title: 'Plastic Moulding & Glass Cutting', content: 'Introduction to plastic moulding processes (injection, compression, blow moulding) and glass cutting techniques. (1 lecture)' },
            { unit: 7, title: 'Metal Casting', content: 'Principles and processes of metal casting: pattern making, mould preparation, pouring, and fettling. (1 lecture)' },
            { unit: 8, title: 'Welding, Brazing', content: 'Arc welding and gas welding processes, equipment, and safety precautions; introduction to brazing and its applications. (1 lecture)' },
          ] },
          { id: 'bt107', name: 'BT-107 - Internship-I (60 Hrs Duration) at the Institute level',                           units: [] },
          { id: 'bt108', name: 'BT-108 - Swachh Bharat Summer Internship / Unnat Bharat Abhiyan (100Hrs)/Rural Outreach',  units: [] },
        ],
      },
      2: {
        label: 'Semester 2',
        subjects: [
          { id: 'bt201', name: 'BT-201 - Engineering Physics', units: [
            { unit: 1, title: 'Wave Nature of Particles & Schrödinger Equation', content: 'Introduction to Quantum mechanics, Wave nature of Particles, operators, Time-dependent and time-independent Schrödinger equation for wavefunction, Application: Particle in a One-dimensional Box, Born interpretation, Free-particle wavefunction and wave-packets, vg and vp relation, Uncertainty principle. (8 lectures)' },
            { unit: 2, title: 'Wave Optics', content: 'Huygens\' principle, superposition of waves and interference of light by wave front splitting and amplitude splitting; Young\'s double slit experiment, Newton\'s rings, Michelson interferometer, Mach-Zehnder interferometer. Fraunhofer diffraction from a single slit and a circular aperture, the Rayleigh criterion for limit of resolution and its application to vision; Diffraction gratings and their resolving power. (8 lectures)' },
            { unit: 3, title: 'Introduction to Solids', content: 'Free electron theory of metals, Fermi level of Intrinsic and extrinsic semiconductors, density of states, Bloch\'s theorem for particles in a periodic potential, Kronig-Penney model (no derivation) and origin of energy bands. V-I characteristics of PN junction, Zener diode, Solar Cell, Hall Effect. (8 lectures)' },
            { unit: 4, title: 'Lasers & Optical Fibers', content: 'Einstein\'s theory of matter radiation interaction and A and B coefficients; amplification of light by population inversion, types of lasers: gas lasers (He-Ne, CO2), solid-state lasers (ruby, Neodymium). Properties of laser beams: monochromaticity, coherence, directionality and brightness, laser speckles, applications in science, engineering and medicine. Introduction to Optical fiber, acceptance angle and cone, Numerical aperture, V number, attenuation. (8 lectures)' },
            { unit: 5, title: 'Electrostatics & Maxwell\'s Equations', content: 'Calculation of electric field and electrostatic potential for a charge distribution; Electric displacement, Basic Introduction to Dielectrics, Gradient, Divergence and Curl, Stokes\' theorem, Gauss Theorem, Continuity equation for current densities; Maxwell\'s equations in vacuum and non-conducting medium; Poynting vector. (8 lectures)' },
          ] },
          { id: 'bt202', name: 'BT-202 - Mathematics-II', units: [
            { unit: 1, title: 'Ordinary Differential Equations – I', content: 'Differential Equations of First Order and First Degree (Leibnitz linear, Bernoulli\'s, Exact), Differential Equations of First Order and Higher Degree, Higher order differential equations with constant coefficients, Homogeneous Linear Differential equations, Simultaneous Differential Equations. (6 hours)' },
            { unit: 2, title: 'Ordinary Differential Equations – II', content: 'Second order linear differential equations with variable coefficients, Method of variation of parameters, Power series solutions; Legendre polynomials, Bessel functions of the first kind and their properties. (8 hours)' },
            { unit: 3, title: 'Partial Differential Equations', content: 'Formulation of Partial Differential equations, Linear and Non-Linear Partial Differential Equations, Homogeneous Linear Partial Differential Equations with Constant Coefficients. (8 hours)' },
            { unit: 4, title: 'Functions of Complex Variable', content: 'Analytic Functions, Harmonic Conjugate, Cauchy-Riemann Equations (without proof), Line Integral, Cauchy-Goursat theorem (without proof), Cauchy Integral formula (without proof), Singular Points, Poles & Residues, Residue Theorem, Application of Residues theorem for Evaluation of Real Integral (Unit Circle). (8 hours)' },
            { unit: 5, title: 'Vector Calculus', content: 'Differentiation of Vectors, Scalar and vector point function, Gradient, Geometrical meaning of gradient, Directional Derivative, Divergence and Curl, Line Integral, Surface Integral and Volume Integral, Gauss Divergence theorem, Stokes\' theorem and Green\'s theorem. (10 hours)' },
          ] },
          { id: 'bt203', name: 'BT-203 - Basic Mechanical Engineering', units: [
            { unit: 1, title: 'Materials', content: 'Classification of engineering materials, Composition of Cast iron and Carbon steels, Iron-Carbon diagram. Alloy steels and their applications. Mechanical properties: strength, hardness, toughness, ductility, brittleness, malleability. Tensile test – Stress-strain diagram of ductile and brittle materials, Hooke\'s law and modulus of elasticity, Hardness and Impact testing, BHN.' },
            { unit: 2, title: 'Measurement & Production Engineering', content: 'Concept of measurements, errors in measurement, Temperature, Pressure, Velocity, Flow, Strain, Force and torque measurement; Vernier caliper, Micrometer, Dial gauge, Slip gauge, Sine-bar and Combination set. Elementary theoretical aspects of production processes: casting, carpentry, welding; Introduction to Lathe and Drilling machines and their various operations.' },
            { unit: 3, title: 'Fluids', content: 'Fluid properties: pressure, density and viscosity. Types of fluids, Newton\'s law of viscosity, Pascal\'s law, Bernoulli\'s equation for incompressible fluids. Working principle of Hydraulic machines, pumps, turbines, Reciprocating pumps.' },
            { unit: 4, title: 'Thermodynamics & Steam Engineering', content: 'Thermodynamic system, properties, state, process; Zeroth, First and Second law of thermodynamics; thermodynamic processes at constant pressure, volume, enthalpy & entropy. Classification and working of boilers, mountings and accessories, efficiency and performance analysis, natural and artificial draught, steam properties, use of steam tables.' },
            { unit: 5, title: 'Reciprocating Machines', content: 'Working principle of steam Engine; Carnot, Otto, Diesel and Dual cycles – P-V & T-S diagrams and efficiency; working of Two-stroke & Four-stroke Petrol & Diesel engines. Working principle of compressors.' },
          ] },
          { id: 'bt204', name: 'BT-204 - Basic Civil Engineering & Mechanics', units: [
            { unit: 1, title: 'Building Materials & Construction', content: 'Stones, bricks, cement, lime, timber – types, properties, tests & uses; laboratory tests on concrete and mortar; Workability and Strength properties of Concrete, Nominal proportion, preparation, compaction, curing. Elements of Building Construction: Foundations (conventional spread footings, RCC footings), brick masonry walls, plastering and pointing, floors, roofs, Doors, windows, lintels, staircases – types and suitability.' },
            { unit: 2, title: 'Surveying & Positioning', content: 'Introduction to surveying instruments – levels, theodolites, plane tables and related devices, electronic surveying instruments. Measurement of distances (conventional and EDM methods), measurement of directions and elevations by different methods, Reciprocal leveling.' },
            { unit: 3, title: 'Mapping & Sensing', content: 'Mapping details and contouring, Profile cross-sectioning and measurement of areas and volumes, application of measurements in quantity computations, Survey stations, Introduction to remote sensing and its applications.' },
            { unit: 4, title: 'Forces and Equilibrium', content: 'Graphical and Analytical Treatment of Concurrent and non-concurrent co-planar forces, Free Body Diagram, Force Diagram and Bow\'s notations. Application of Equilibrium Concepts: Analysis of plane Trusses by Method of Joints and Method of Sections. Frictional force in equilibrium problems.' },
            { unit: 5, title: 'Centre of Gravity & Moment of Inertia', content: 'Centroid and Centre of Gravity, Moment of Inertia of Area and Mass, Radius of Gyration, Introduction to product of Inertia and Principal Axes. Support Reactions, Shear force and Bending Moment Diagrams for Cantilever & simply supported beams with concentrated load, distributed load and Couple.' },
          ] },
          { id: 'bt205', name: 'BT-205 - Basic Computer Engineering', units: [
            { unit: 1, title: 'Computer Organization & Operating Systems', content: 'Computer definition, Classification, Organization: CPU, register, Bus architecture, Instruction set, Memory & Storage Systems, I/O Devices, System & Application Software. Computer Applications in eBusiness, Bio-Informatics, Health Care, Remote Sensing & GIS, Meteorology, Gaming, Multimedia and Animation. Operating System: Definition, Function, Types, Management of File, Process & Memory. Introduction to MS Word, MS PowerPoint, MS Excel.' },
            { unit: 2, title: 'Algorithms, Flowcharts & Introduction to C++', content: 'Introduction to Algorithms, Complexities and Flowchart, Categories of Programming Languages, Program Design, Programming Paradigms, OOP concepts, Procedure Oriented vs Object Oriented Programming. Introduction to C++: Character Set, Tokens, Precedence and Associativity, Program Structure, Data Types, Variables, Operators, Expressions, Statements and control structures, I/O operations, Array, Functions.' },
            { unit: 3, title: 'Object Oriented Programming & Data Structures', content: 'Object & Classes, Scope Resolution Operator, Constructors & Destructors, Friend Functions, Inheritance, Polymorphism, Overloading Functions & Operators, Types of Inheritance, Virtual functions. Introduction to Data Structures.' },
            { unit: 4, title: 'Computer Networking & Cyber Security', content: 'Computer Networking: Introduction, Goals, ISO-OSI Model, Functions of Different Layers, Internetworking Concepts & Devices, TCP/IP Model, Internet, WWW, E-commerce. Computer Security Basics: viruses, worms, malware, Trojans, Spyware; types of attacks (Money Laundering, Information Theft, Cyber Pornography, Email Spoofing, DoS, Cyber Stalking, Logic Bombs, Hacking, Spamming, Pharming); Security measures, Firewall, Computer Ethics, Introduction to Cyber Laws.' },
            { unit: 5, title: 'DBMS & Cloud Computing', content: 'Database Management System: Introduction, File-oriented vs Database approach, Data Models, Architecture, Data independence, Data dictionary, DBA, Primary Key, DDL and DML. Cloud Computing: definition, cloud infrastructure, service delivery models (IaaS, PaaS, SaaS), cloud deployment models (public, private, community, hybrid clouds), Pros and Cons of cloud computing.' },
          ] },
          { id: 'bt206', name: 'BT-206 - Language Lab & Seminars', units: [] },
        ],
      },
    },
  },

  // ══════════════════════════════════════════════
  //  SECOND YEAR (Sem 3 & 4)
  // ══════════════════════════════════════════════
  'second-year': {
    label: 'Second Year',
    semesters: {
      3: {
        label: 'Semester 3',
        subjects: [
          { id: 'es301', name: 'ES-301 - Energy & Environmental Engineering', units: [
            { unit: 1, title: 'Introduction to Energy Science', content: 'Introduction to energy systems and resources; sustainability & the environment; Overview of energy systems, sources, transformations, efficiency, and storage; Fossil fuels (coal, oil, oil-bearing shale and sands, coal gasification) past, present & future; Remedies & alternatives: biomass, wind, solar, nuclear, wave, tidal and hydrogen; Sustainability and environmental trade-offs; possibilities for energy storage or regeneration (e.g. Pumped storage hydro power projects, superconductor-based energy storages, high efficiency batteries).' },
            { unit: 2, title: 'Ecosystems', content: 'Concept of an ecosystem; Structure and function of an ecosystem; Producers, consumers and decomposers; Energy flow in the ecosystem; Ecological succession; Food chains, food webs and ecological pyramids; Types and structure of ecosystems: Forest, Grassland, Desert, and Aquatic ecosystems (ponds, streams, lakes, rivers, oceans, estuaries).' },
            { unit: 3, title: 'Biodiversity & Its Conservation', content: 'Definition: genetic, species and ecosystem diversity; Biogeographical classification of India; Value of biodiversity: consumptive use, productive use, social, ethical, aesthetic and option values; Biodiversity at global, National and local levels; India as a mega-diversity nation; Hot-spots of biodiversity; Threats: habitat loss, poaching of wildlife, man-wildlife conflicts; Endangered and endemic species of India; Conservation: In-situ and Ex-situ conservation of biodiversity.' },
            { unit: 4, title: 'Environmental Pollution', content: 'Definition, Cause, effects and control measures of Air, Water, Soil, Marine, Noise, Thermal pollution and Nuclear hazards; Solid Waste Management: Causes, effects and control measures of urban and industrial wastes; Role of an individual in prevention of pollution; Pollution case studies; Disaster management: floods, earthquake, cyclone and landslides.' },
            { unit: 5, title: 'Social Issues & the Environment', content: 'Unsustainable to Sustainable development; Urban problems related to energy; Water conservation, rain water harvesting, watershed management; Resettlement and rehabilitation issues. Environmental ethics, Climate change, global warming, acid rain, ozone layer depletion, nuclear accidents. Wasteland reclamation; Consumerism and waste products; Environment Protection Act; Air & Water (Prevention and Control of Pollution) Acts; Wildlife Protection Act; Forest Conservation Act; Public awareness.' },
            { unit: 6, title: 'Field Work', content: 'Visit to a local area to document environmental assets: river/forest/grassland/hill/mountain; Visit to a local polluted site: Urban/Rural/Industrial/Agricultural; Study of common plants, insects, birds; Study of simple ecosystems: pond, river, hill slopes, etc.' },
          ] },
          { id: 'cs302', name: 'CS-302 - Discrete Structure', units: [
            { unit: 1, title: 'Set Theory, Relations, Functions & Theorem Proving', content: 'Set Theory: Definition, countable and uncountable sets, Venn Diagrams, identities on sets. Relations: types, composition, Pictorial representation, Equivalence relation, Partial ordering, Job-Scheduling problem. Functions: types, one to one, into and onto, inverse, composition, recursively defined functions, pigeonhole principle. Theorem Proving: Mathematical induction, Proof by contradiction.' },
            { unit: 2, title: 'Algebraic Structures', content: 'Definition, Properties, types: Semi Groups, Monoid, Groups, Abelian group, properties of groups, Subgroup, cyclic groups, Cosets, factor group, Permutation groups, Normal subgroup, Homomorphism and isomorphism of Groups. Rings and Fields: definition and standard results.' },
            { unit: 3, title: 'Propositional Logic & Finite State Machines', content: 'Proposition, First order logic, Basic logical operations, truth tables, tautologies, Contradictions, Algebra of Proposition, logical implications, logical equivalence, predicates, Normal Forms, Universal and existential quantifiers. Introduction to finite state machines as models of physical systems, equivalence machines, and language recognizers.' },
            { unit: 4, title: 'Graph Theory', content: 'Introduction and basic terminology of graphs, Planer graphs, Multigraphs and weighted graphs, Isomorphic graphs, Paths, Cycles and connectivity, Shortest path in weighted graph, Eulerian paths and circuits, Hamiltonian paths and circuits, Graph coloring, chromatic number, Isomorphism and Homomorphism of graphs.' },
            { unit: 5, title: 'Posets, Lattices & Combinatorics', content: 'Posets, Hasse Diagram and Lattices: ordered set, Hasse diagram, isomorphic ordered set, well ordered set, properties of Lattices, bounded and complemented lattices. Combinatorics: Permutation and combination, Binomial Theorem, Multinomial Coefficients. Recurrence Relation and Generating Functions: Linear recurrence relations with constant coefficients, Homogeneous, Particular & Total solutions, Generating functions and their applications.' },
          ] },
          { id: 'cs303', name: 'CS-303 - Data Structure', units: [
            { unit: 1, title: 'Introduction to Data Structures & Linked Lists', content: 'Review of C programming language. Concepts of Data and Information, Classification of Data structures, Abstract Data Types, Memory representation. Data structures operations and cost estimation. Introduction to linear data structures: Arrays. Linked List: Representation in memory, different implementations, Circular linked list, doubly linked list. Application: polynomial manipulation using linked list.' },
            { unit: 2, title: 'Stacks & Queues', content: 'Stacks as ADT, different implementations, multiple stacks. Applications: Conversion of infix to postfix notation, evaluation of postfix expression, Recursion. Queues as ADT, different implementations, Circular queue, Deque and Priority Queue, Queue simulation and applications.' },
            { unit: 3, title: 'Trees', content: 'Definitions: Height, depth, order, degree. Binary Search Tree: Operations, Traversal, Search. AVL Tree, Heap, Applications and comparison of various types of trees; Introduction to forest, multi-way tree, B tree, B+ tree, B* tree and red-black tree.' },
            { unit: 4, title: 'Graphs', content: 'Introduction, Classification: Directed and Undirected graphs, Representation. Graph Traversal: DFS and BFS. Graph algorithms: Minimum Spanning Tree (MST): Kruskal and Prim algorithms. Dijkstra shortest path algorithm; Comparison between different graph algorithms and their applications.' },
            { unit: 5, title: 'Sorting, Searching & Hashing', content: 'Sorting: Bubble Sort, Quick Sort, Selection Sort, Heap Sort, Insertion Sort, Shell Sort, Merge Sort and Radix Sort; comparison of sorting techniques. Searching: Sequential search, Binary search, comparison of search methods. Hashing & Indexing. Case Study: Application of data structures in OS, DBMS, etc.' },
          ] },
          { id: 'cs304', name: 'CS-304 - Digital Systems', units: [
            { unit: 1, title: 'Number Systems & Boolean Algebra', content: 'Review of number systems and number base conversions. Binary codes, Boolean algebra, Boolean functions, Logic gates. Simplification of Boolean functions, Karnaugh map methods, SOP-POS simplification, NAND-NOR implementation.' },
            { unit: 2, title: 'Combinational Logic', content: 'Half adder, Half subtractor, Full adder, Full subtractor, Look-ahead carry generator, BCD adder, Series and parallel addition, Multiplexer and Demultiplexer, Encoder and Decoder, Arithmetic circuits, ALU.' },
            { unit: 3, title: 'Sequential Logic & Memories', content: 'Flip flops: D, T, S-R, J-K Master-Slave, racing condition, Edge & Level triggered circuits. Shift registers, Asynchronous and synchronous counters, state diagrams. Semiconductor memories, digital ICs 2716, 2732 and address decoding. Modern trends: DRAM, FLASH RAM. Designing with ROM and PLA.' },
            { unit: 4, title: 'A/D & D/A Converters & Multivibrators', content: 'Introduction to A/D & D/A converters and their types, sample and hold circuits, Voltage to Frequency & Frequency to Voltage conversion. Multivibrators: Bistable, Monostable, Astable, Schmitt trigger, IC 555 & its applications. TTL, PMOS, CMOS and NMOS logic. Interfacing between TTL to MOS.' },
            { unit: 5, title: 'Introduction to Digital Communication', content: 'Nyquist sampling theorem, Time Division Multiplexing, PCM, quantization error, Introduction to BPSK & BFSK modulation schemes. Shannon theorem for channel capacity.' },
          ] },
          { id: 'cs305', name: 'CS-305 - Object Oriented Programming & Methodology', units: [
            { unit: 1, title: 'Introduction to OOP', content: 'Introduction to Object Oriented Thinking & OOP: Comparison with Procedural Programming, features of OO paradigm: merits and demerits; Object model; Elements of OOPS, IO processing.' },
            { unit: 2, title: 'Encapsulation & Data Abstraction', content: 'Concept of Objects: State, Behavior & Identity; Classes: identifying classes and candidates, Attributes and Services, Access modifiers, Static members, Instances, Message passing, Construction and destruction of Objects.' },
            { unit: 3, title: 'Relationships & Inheritance', content: 'Inheritance: purpose and types, "is a" relationship; Association, Aggregation. Concept of interfaces and Abstract classes.' },
            { unit: 4, title: 'Polymorphism', content: 'Introduction to Polymorphism, Method Overriding & Overloading, static and runtime Polymorphism.' },
            { unit: 5, title: 'Strings, Exception Handling & Multithreading', content: 'Strings, Exceptional handling, Introduction to Multi-threading and Data collections. Case studies: ATM system, Library management system.' },
          ] },
          { id: 'cs306', name: 'CS-306 - Computer Workshop',                                                               units: [] },
          { id: 'bt107e', name: 'BT-107 - Evaluation of Internship-I (completed at I year level)',                        units: [] },
          { id: 'bt307', name: 'BT-307 - 90 hrs Internship based on using various softwares – Internship-II',             units: [] },
        ],
      },
      4: {
        label: 'Semester 4',
        subjects: [
          { id: 'bt401',  name: 'BT-401 - Mathematics-III', units: [
            { unit: 1, title: 'Numerical Methods – I', content: 'Solution of polynomial and transcendental equations: Bisection method, Newton-Raphson method and Regula-Falsi method. Finite differences, Relation between operators, Interpolation using Newton forward and backward difference formulae. Interpolation with unequal intervals: Newton divided difference and Lagrange formulae. (8 hours)' },
            { unit: 2, title: 'Numerical Methods – II', content: 'Numerical Differentiation, Numerical Integration: Trapezoidal rule and Simpson 1/3rd and 3/8 rules. Solution of Simultaneous Linear Algebraic Equations by Gauss Elimination, Gauss-Jordan, Crout method, Jacobi, Gauss-Seidel, and Relaxation method. (6 hours)' },
            { unit: 3, title: 'Numerical Methods – III', content: 'Ordinary differential equations: Taylor series, Euler and modified Euler methods. Runge-Kutta method of fourth order for first and second order equations. Milne and Adam predictor-corrector methods. Partial differential equations: Finite difference solution for 2D Laplace and Poisson equations, Implicit and explicit methods for 1D heat equation (Bender-Schmidt and Crank-Nicholson), Finite difference explicit method for wave equation. (10 hours)' },
            { unit: 4, title: 'Transform Calculus', content: 'Laplace Transform, Properties of Laplace Transform, Laplace transform of periodic functions. Finding inverse Laplace transform by different methods, convolution theorem. Evaluation of integrals by Laplace transform, solving ODEs by Laplace Transform method, Fourier transforms. (8 hours)' },
            { unit: 5, title: 'Concept of Probability', content: 'Probability Mass function, Probability Density Function. Discrete Distributions: Binomial, Poisson. Continuous Distributions: Normal Distribution, Exponential Distribution. (8 hours)' },
          ] },
          { id: 'cs402',  name: 'CS-402 - Analysis Design of Algorithm', units: [
            { unit: 1, title: 'Algorithms & Divide and Conquer', content: 'Algorithms, Designing algorithms, analyzing algorithms, asymptotic notations, heap and heap sort. Introduction to divide and conquer technique: analysis, design and comparison of algorithms such as binary search, merge sort, quick sort, Strassen matrix multiplication.' },
            { unit: 2, title: 'Greedy Strategy', content: 'Study of Greedy strategy with examples: optimal merge patterns, Huffman coding, minimum spanning trees, knapsack problem, job sequencing with deadlines, single source shortest path algorithm.' },
            { unit: 3, title: 'Dynamic Programming', content: 'Concept of dynamic programming and problems: 0/1 knapsack, multistage graph, reliability design, Floyd-Warshall algorithm.' },
            { unit: 4, title: 'Backtracking & Branch and Bound', content: 'Backtracking concept with examples: 8 queens problem, Hamiltonian cycle, Graph coloring problem. Introduction to branch and bound method: traveling salesman problem. Meaning of lower bound theory and its use in solving algebraic problems, introduction to parallel algorithms.' },
            { unit: 5, title: 'Trees, Graphs & NP-Completeness', content: 'Binary search trees, height balanced trees, 2-3 trees, B-trees. Basic search and traversal techniques for trees and graphs (Inorder, Preorder, Postorder, DFS, BFS). NP-completeness.' },
          ] },
          { id: 'cs403',  name: 'CS-403 - Software Engineering', units: [
            { unit: 1, title: 'Software Product & Process', content: 'Software Product and Process Characteristics; Software Process Models: Linear-Sequential, Prototyping, RAD Model; Evolutionary Process Models: Incremental, Spiral, Component Assembly Model, RUP and Agile processes. Software Process customization and improvement, CMM, Product and Process Metrics.' },
            { unit: 2, title: 'Requirement Elicitation, Analysis & Specification', content: 'Functional and Non-functional requirements, Requirement Sources and Elicitation Techniques, Analysis Modeling for Function-oriented and Object-oriented software development, Use case Modeling, System and Software Requirement Specifications, Requirement Validation, Traceability.' },
            { unit: 3, title: 'Software Design', content: 'The Software Design Process, Design Concepts and Principles, Software Modeling and UML, Architectural Design, Architectural Views and Styles, User Interface Design, Function-oriented Design (SA/SD), Component Based Design, Design Metrics.' },
            { unit: 4, title: 'Software Analysis & Testing', content: 'Software Static and Dynamic analysis, Code inspections, Software Testing Fundamentals, Test Process, Testing Levels, Test Criteria, Test Case Design, Test Oracles, Test Techniques, Black-Box Testing, White-Box Unit Testing and Unit Testing Frameworks, Integration Testing, System Testing, Test Plan, Test Metrics, Testing Tools. Introduction to OO analysis and design.' },
            { unit: 5, title: 'Software Maintenance & Project Management', content: 'Types of Maintenance, Software Configuration Management (SCM), Change Management, Version Control, Change Control and Reporting, Program Comprehension Techniques, Re-engineering, Reverse Engineering. Project Management: Feasibility Analysis, Project and Process Planning, Resource Allocation, Software Effort, Schedule and Cost estimations, Project Scheduling and Tracking, Risk Assessment and Mitigation, Software Quality Assurance (SQA), Project Metrics.' },
          ] },
          { id: 'cs404',  name: 'CS-404 - Computer Organisation & Architecture', units: [
            { unit: 1, title: 'Basic Structure of Computer & Control Unit', content: 'Structure of Desktop Computers, CPU: General Register Organization, Memory Register, Instruction Register, Control Word, Stack Organization, Instruction Format, ALU, I/O System, bus, Program Counter, Bus Structure, Register Transfer Language, Addressing modes. Control Unit: Instruction types, Micro Instruction Formats, Fetch and Execution cycle, Hardwired control unit, Microprogrammed Control unit, microprogram sequencer, Control Memory, Sequencing and Execution of Micro Instructions.' },
            { unit: 2, title: 'Computer Arithmetic', content: 'Addition and Subtraction, Two Complement Representation, Signed Addition and Subtraction, Multiplication and Division, Booth Algorithm, Division Operation, Floating Point Arithmetic Operations. Design of Arithmetic unit.' },
            { unit: 3, title: 'I/O Organization', content: 'I/O Interface: PCI Bus, SCSI Bus, USB. Data Transfer: Serial, Parallel, Synchronous, Asynchronous modes. Direct Memory Access (DMA), I/O Processor.' },
            { unit: 4, title: 'Memory Organization', content: 'Main memory: RAM, ROM. Secondary Memory: Magnetic Tape, Disk, Optical Storage. Cache Memory: Cache Structure and Design, Mapping Scheme, Replacement Algorithm, Improving Cache Performance. Virtual Memory and memory management hardware.' },
            { unit: 5, title: 'Multiprocessors & Advanced Architectures', content: 'Characteristics of Multiprocessor, Structure: Interprocessor Arbitration, Communication and Synchronization. Memory in Multiprocessor Systems. Concept of Pipelining, Vector Processing, Array Processing, RISC and CISC. Study of Multicore Processors: Intel, AMD.' },
          ] },
          { id: 'cs405',  name: 'CS-405 - Operating Systems', units: [
            { unit: 1, title: 'Introduction to Operating Systems', content: 'Function, Evolution, Different Types, Desirable Characteristics and features of an OS. OS Services: Types of Services, Different ways of providing services: Utility Programs, System Calls.' },
            { unit: 2, title: 'File Systems', content: 'File Concept, User and System Programmer view of File System, Disk Organization, Tape Organization, Different Modules of a File System, Disk Space Allocation Methods: Contiguous, Linked, Indexed. Directory Structures, File Protection, System Calls for File Management, Disk Scheduling Algorithms.' },
            { unit: 3, title: 'CPU Scheduling & Memory Management', content: 'Process Concept, Scheduling Concepts, Types of Schedulers, Process State Diagram, Scheduling Algorithms, Algorithms Evaluation, System calls for Process Management; Multiple Processor Scheduling; Concept of Threads. Memory Management: Partitioning, Swapping, Segmentation, Paging, Paged Segmentation; Techniques for large programs: Overlay, Dynamic Linking and Loading; Virtual Memory: Demand Paging.' },
            { unit: 4, title: 'I/O & Concurrent Processes', content: 'Input/Output: Principles and Programming, Asynchronous Operations, Speed gap Format conversion, I/O Interfaces, Programme Controlled I/O, Interrupt Driven I/O, Concurrent I/O. Concurrent Processes: Mutual Exclusion, Synchronization, Inter-Process Communication, Critical Section Problem, Semaphores (Binary and Counting), WAIT and SIGNAL Operations. Deadlocks: Characterization, Prevention, Avoidance, Recovery.' },
            { unit: 5, title: 'Network, Distributed & Multiprocessor OS', content: 'Introduction to Network, Distributed and Multiprocessor Operating Systems. Case Studies: Unix/Linux, WINDOWS and other Contemporary Operating Systems.' },
          ] },
          // CS-406 Electives — student chooses one
          { id: 'cs406a', name: 'CS-406 - Programming Practices (Java)', isElective: true, electiveGroup: 'CS-406', units: [
            { unit: 1, title: 'Basic Java Features', content: 'C++ Vs Java, Java Virtual Machine, Constants and Variables, Data Types, Class, Methods, Objects, Strings and Arrays, Type Casting, Operators, Precedence, Control Statements, Exception Handling, File and Streams, Visibility, Constructors, Operator and Method Overloading, Static Members, Inheritance, Polymorphism, Abstract methods and Classes.' },
            { unit: 2, title: 'Java Collections Framework', content: 'Data Structures: Type-Wrapper Classes, Dynamic Memory Allocation, Linked List, Stack, Queues, Trees. Generics: Overloading Generic Methods, Generic Classes. Collections: Interface Collection and Class Collections, Lists, ArrayList, LinkedList, Vector. Collections Algorithms: sort, shuffle, reverse, fill, copy, max, min, binary Search, addAll. Stack, Priority Queue, Maps, Properties Class, Unmodifiable Collections.' },
            { unit: 3, title: 'Advanced Java Features', content: 'Multithreading: Thread States, Priorities, Life Cycle, Thread Synchronization, Creating and Executing Threads, Multithreading with GUI, Monitors and Monitor Locks. Networking: Manipulating URLs, Reading files on a Web Server, Socket programming, Security, RMI. Accessing Databases with JDBC: Relational Database, SQL, MySQL, Oracle.' },
            { unit: 4, title: 'Advanced Java Technologies', content: 'Servlets: Overview and Architecture, Apache Tomcat Server, Handling HTTP GET Requests, Deploying Web Applications, Multitier Applications, JDBC from a Servlet. Java Server Pages (JSP): Overview, Implicit Objects, Scripting, Standard Actions, Directives. Multimedia: Applets and Applications: Loading, Displaying and Scaling Images, Animating Images, Loading and playing Audio clips.' },
            { unit: 5, title: 'Advanced Web/Internet Programming', content: 'Overview of J2ME, J2EE, EJB, XML.' },
          ] },
          { id: 'cs406b', name: 'CS-406 - Programming Practices (.NET)',                                                   units: [], isElective: true, electiveGroup: 'CS-406' },
          { id: 'cs406c', name: 'CS-406 - Programming Practices (Python)',                                                 units: [], isElective: true, electiveGroup: 'CS-406' },
          { id: 'cs406d', name: 'CS-406 - Programming Practices (MATLAB)',                                                 units: [], isElective: true, electiveGroup: 'CS-406' },
          { id: 'bt407',  name: 'BT-407 - 90 hrs Internship based on using various softwares – Internship-II',           units: [] },
          { id: 'bt408',  name: 'BT-408 - Cyber Security',                                                                units: [] },
        ],
      },
    },
  },

  // ══════════════════════════════════════════════
  //  THIRD YEAR (Sem 5 & 6)
  // ══════════════════════════════════════════════
  'third-year': {
    label: 'Third Year',
    semesters: {
      5: {
        label: 'Semester 5',
        subjects: [
          { id: 'cs501',  name: 'CS-501 - Theory of Computation', units: [
            { unit: 1, title: 'Introduction to Automata Theory', content: 'Examples of automata machines, Finite Automata as a language acceptor and translator, Moore machines and Mealy machines, composite machine, Conversion from Mealy to Moore and vice versa.' },
            { unit: 2, title: 'Types of Finite Automata', content: 'Non Deterministic Finite Automata (NDFA), Deterministic Finite Automata (DFA), conversion of NDFA to DFA, minimization of automata machines, regular expression, Arden theorem. Meaning of union, intersection, concatenation and closure, 2-way DFA.' },
            { unit: 3, title: 'Grammars', content: 'Types of grammar, context sensitive grammar, context free grammar, regular grammar. Derivation trees, ambiguity in grammar, simplification of context free grammar, conversion of grammar to automata and vice versa, Chomsky hierarchy of grammar, killing null and unit productions. Chomsky Normal Form and Greibach Normal Form.' },
            { unit: 4, title: 'Push Down Automata', content: 'Example of PDA, deterministic and non-deterministic PDA, conversion of PDA into context free grammar and vice versa, CFG equivalent to PDA, Petri net model.' },
            { unit: 5, title: 'Turing Machine & Decidability', content: 'Techniques for construction of Turing Machine. Universal Turing machine, Multitape, multihead and multidimensional Turing machine, N-P complete problems. Decidability and Recursively Enumerable Languages: decidable languages, undecidable languages, Halting problem of Turing machine and the Post Correspondence Problem.' },
          ] },
          { id: 'cs502',  name: 'CS-502 - Database Management Systems', units: [
            { unit: 1, title: 'DBMS Concepts & Architecture', content: 'Introduction, Database approach vs Traditional file accessing approach, Advantages of database systems, Data models, Schemas and instances, Data independence, Database Languages and interfaces, Overall Database Structure, Functions of DBA and designer. ER data model: Entities and attributes, Entity types, Defining the E-R diagram, Generalization, Aggregation and Specialization, transforming ER diagram into tables. Object oriented, Network, and Relational data models: comparison.' },
            { unit: 2, title: 'Relational Data Models & Query Languages', content: 'Domains, Tuples, Attributes, Relations, Characteristics of relations, Keys, Relational database Schemas, Integrity constraints, Referential integrity, Intension and Extension. SQL: DDL, DML, integrity constraints, complex queries, joins, indexing, triggers, assertions. Relational algebra: select, project, join, division, outer union. Relational calculus: Tuple oriented and domain oriented.' },
            { unit: 3, title: 'Database Design & Query Optimization', content: 'Introduction to normalization, Normal forms, Functional dependency, Decomposition, Dependency preservation and lossless join, problems with null valued and dangling tuples, multivalued dependencies. Query Optimization: Introduction, steps of optimization, algorithms to implement select, project and join operations, heuristic based and cost estimation based optimization methods.' },
            { unit: 4, title: 'Transaction Processing & Concurrency Control', content: 'Transaction System, Testing of Serializability, Serializability of schedules, conflict and view serializable schedule, recoverability, Recovery from transaction failures, Log based recovery, Checkpoints, deadlock handling. Concurrency Control: locking techniques, time stamping protocols, validation based protocol, multiple granularity, multi version schemes. Introduction to Distributed databases, data mining, data warehousing, OODBMS vs DBMS.' },
            { unit: 5, title: 'RDBMS through Oracle/PL SQL/MySQL', content: 'Architecture, physical files, memory structures, background process. Table spaces, segments, extents and blocks. Dedicated server, multi-threaded server. Distributed database, database links, snapshots. Data dictionary, dynamic performance view. Security, role and privilege management, profiles. SQL queries: single and multiple tables, various joins, special operators (like, any, all, exists, in), hierarchical queries, inline queries, flashback queries. ANSI SQL, anonymous blocks, cursors, exception handling, stored procedures, user-defined functions, triggers, mutating errors, instead of triggers.' },
          ] },
          // CS-503 Electives — student chooses one
          { id: 'cs503a', name: 'CS-503 - Data Analytics', isElective: true, electiveGroup: 'CS-503', units: [
            { unit: 1, title: 'Descriptive Statistics', content: 'Probability Distributions, Inferential Statistics through hypothesis tests, Regression and ANOVA (Analysis of Variance).' },
            { unit: 2, title: 'Introduction to Big Data & Technologies', content: 'Big Data and its Importance, Four Vs of Big Data, Drivers for Big Data, Introduction to Big Data Analytics, Big Data Analytics applications. Hadoop Parallel World, Data discovery, Open source technology for Big Data Analytics, cloud and Big Data, Predictive Analytics, Mobile Business Intelligence, Crowd Sourcing Analytics, Information Management.' },
            { unit: 3, title: 'Processing Big Data', content: 'Integrating disparate data stores, Mapping data to the programming framework, Connecting and extracting data from storage, Transforming data for processing, subdividing data in preparation for Hadoop MapReduce.' },
            { unit: 4, title: 'Hadoop MapReduce', content: 'Employing Hadoop MapReduce, Creating components of MapReduce jobs, Distributing data processing across server farms, Executing and monitoring MapReduce jobs. Building Blocks: Hadoop daemons, Hadoop Distributed File System, execution modes (local, pseudo-distributed, fully distributed).' },
            { unit: 5, title: 'Big Data Tools & Techniques', content: 'Installing and Running Pig, Comparison with Databases, Pig Latin, User-Defined Functions, Data Processing Operators. Installing and Running Hive, Hive QL, Querying Data, User-Defined Functions, Oracle Big Data.' },
          ] },
          { id: 'cs503b', name: 'CS-503 - Pattern Recognition', isElective: true, electiveGroup: 'CS-503', units: [
            { unit: 1, title: 'Introduction to Pattern Recognition', content: 'Definitions, data sets for Pattern, Application Areas and Examples of pattern recognition, Design principles of pattern recognition system, Classification and clustering, supervised and unsupervised learning, Pattern recognition approaches, Decision Boundaries, Decision region, Metric spaces, distances.' },
            { unit: 2, title: 'Classification', content: 'Introduction, application and types of classification, decision tree, naive Bayes, logistic regression, support vector machine, random forest, K Nearest Neighbour Classifier and variants, Efficient algorithms for nearest neighbour classification, Different Approaches to Prototype Selection, Combination of Classifiers, Training set, test set, standardization and normalization.' },
            { unit: 3, title: 'Clustering & Unsupervised Learning', content: 'Different Paradigms of Pattern Recognition, Representations of Patterns and Classes, Unsupervised Learning and Clustering: Criterion functions for clustering, Clustering Techniques: K-means (iterative square-error partitional), hierarchical clustering, Cluster validation.' },
            { unit: 4, title: 'Feature Extraction & Selection', content: 'Introduction to feature extraction and feature selection, types of feature extraction, Problem statement and Uses. Algorithms: Branch and bound algorithm, sequential forward/backward selection algorithms, (l,r) algorithm.' },
            { unit: 5, title: 'Recent Advances in Pattern Recognition', content: 'Recent advances in Pattern Recognition, Structural PR, SVMs, FCM, Soft computing and Neuro-fuzzy techniques, real-life examples, Histograms rules, Density Estimation, Nearest Neighbor Rule, Fuzzy classification.' },
          ] },
          { id: 'cs503c', name: 'CS-503 - Cyber Security', isElective: true, electiveGroup: 'CS-503', units: [
            { unit: 1, title: 'Introduction to Cyber Crime', content: 'Introduction of Cyber Crime, Challenges of cyber crime, Classifications of Cybercrimes: Email Spoofing, Spamming, Internet Time Theft, Salami attack/Salami Technique.' },
            { unit: 2, title: 'Types of Cyber Crimes', content: 'Web jacking, Online Frauds, Software Piracy, Computer Network Intrusions, Password Sniffing, Identity Theft, cyber terrorism, Virtual Crime, Perception of cyber criminals: hackers, insurgents and extremist groups. Web server hacking, session hijacking.' },
            { unit: 3, title: 'Cyber Crime & Criminal Justice', content: 'Concept of Cyber Crime and the IT Act 2000, Hacking, Teenage Web Vandals, Cyber Fraud and Cheating, Defamation, Harassment and E-mail Abuse, Other IT Act Offences, Monetary Penalties, jurisdiction and Cyber Crimes, Nature of Criminality, Strategies to tackle Cyber Crime and Trends.' },
            { unit: 4, title: 'Indian Evidence Act vs IT Act 2000', content: 'Status of Electronic Records as Evidence, Proof and Management of Electronic Records; Relevancy, Admissibility and Probative Value of E-Evidence, Proving Digital Signatures, Proof of Electronic Agreements, Proving Electronic Messages.' },
            { unit: 5, title: 'Tools & Methods in Cybercrime', content: 'Proxy Servers and Anonymizers, Password Cracking, Key loggers and Spyware, Virus and Worms, Trojan Horses, Backdoors, DoS and DDoS Attacks, Buffer Overflow, Attack on Wireless Networks, Phishing: Methods and Techniques.' },
          ] },
          // CS-504 Electives — student chooses one
          { id: 'cs504a', name: 'CS-504 - Internet and Web Technology', isElective: true, electiveGroup: 'CS-504', units: [
            { unit: 1, title: 'Introduction to WWW & Web Design', content: 'Concept of WWW, Internet and WWW, HTTP Protocol: Request and Response, Web browser and Web servers, Features of Web 2.0. Web Design: Concepts of effective web design, Web design issues including Browser, Bandwidth and Cache, Display resolution, Look and Feel, Page Layout and linking, User centric design, Sitemap, Planning and publishing website, Designing effective navigation.' },
            { unit: 2, title: 'HTML & HTML5', content: 'Basics of HTML, formatting and fonts, commenting code, color, hyperlink, lists, tables, images, forms, XHTML, Meta tags, Character entities, frames and frame sets, Browser architecture and Web site structure. Overview and features of HTML5.' },
            { unit: 3, title: 'CSS, JavaScript & DHTML', content: 'CSS: Need, basic syntax and structure, background images, colors, manipulating texts, fonts, borders, boxes, margins, padding, lists, positioning, CSS2, Overview of CSS3. JavaScript: Client side scripting, variables, functions, conditions, loops, Pop up boxes, JavaScript objects, the DOM, Manipulation using DOM, forms and validations. DHTML: Combining HTML, CSS and JavaScript, Events and buttons.' },
            { unit: 4, title: 'XML & PHP', content: 'XML: Introduction, uses, simple XML, XML key components, DTD and Schemas, Using XML with applications, transforming XML using XSL and XSLT. PHP: Introduction and basic syntax, decision and looping, PHP and HTML, Arrays, Functions, Browser control and detection, string handling, Form processing, Files, Cookies and Sessions, OOP with PHP.' },
            { unit: 5, title: 'PHP & MySQL', content: 'Basic commands with PHP examples, Connection to server, creating database, selecting a database, listing databases, listing table names, creating a table, inserting data, altering tables, queries, deleting database, deleting data and tables, PHP myadmin and database bugs.' },
          ] },
          { id: 'cs504b', name: 'CS-504 - Object Oriented Programming',                                                   units: [], isElective: true, electiveGroup: 'CS-504' },
          { id: 'cs504c', name: 'CS-504 - Introduction to Database Management Systems', isElective: true, electiveGroup: 'CS-504', units: [
            { unit: 1, title: 'DBMS Concepts', content: 'Introduction, Significance of Database, Database System Applications; Data Independence; Data Modeling for a Database; Entities and their Attributes, Relationships and Relationship Types, Advantages and Disadvantages of DBMS, DBMS Vs RDBMS.' },
            { unit: 2, title: 'Database Models & Implementation', content: 'Data Model and Types: Relational Data Model, Hierarchical Model, Network Data Model, Object/Relational Model, Object-Oriented Model; Entity-Relationship Model, Modeling using E-R Diagrams, Notation used in E-R Model, Relationships and Relationship Types; Associative Database Model.' },
            { unit: 3, title: 'SQL – Data Definition Language', content: 'Categories of SQL Commands; Data Definition Language: Create table, Drop table and Alter Table. Primary Key, Foreign Key, Truncate Table, Index, Cursor.' },
            { unit: 4, title: 'SQL – Data Manipulation Language', content: 'Insert Statement, Multiple Inserts, Delete Statement, Delete with conditions, Update statement, Update with Conditions, Merge Statement.' },
            { unit: 5, title: 'SELECT & Advanced Queries', content: 'SQL queries, Data extraction from single and multiple tables: equi-join, non equi-join, self-join, outer join. Usage of like, any, all, exists, in special operators. Hierarchical queries, inline queries, flashback queries. Introduction of ANSI SQL, anonymous block, nested anonymous block, branching and looping constructs in ANSI SQL.' },
          ] },
          { id: 'cs505',  name: 'CS-505 - Lab (Linux)', units: [
            { unit: 1, title: 'Overview of Unix/Linux', content: 'Concepts, Unix/Linux Installation Process, Hardware Requirements, Advantages of Unix/Linux, Reasons for Popularity and Success, Features of Linux/Unix Operating System, Kernel, Kernel Functions.' },
            { unit: 2, title: 'Shell Basic Commands & Shell Programming', content: 'Shell Variables, Branching Control Structures, Loop-Control Structure, Continue and break Statements, Sleep Command, Debugging Script. Use of Linux as webserver, file server, directory server, application server, DNS server, SMTP server, Firewall, Proxy server.' },
            { unit: 3, title: 'File System', content: 'Definition of File System, Defining Geometry, Disk Controller, Solaris File System, Disk Based File Systems, Network-Based File Systems, Virtual File systems, UFS File System, The Boot Block, The Super Block, The Inode, Tuning and Repairing File System.' },
            { unit: 4, title: 'Process Control', content: 'Viewing a Process, Command to display Process, Process Attributes, Process States, Process Fields, PS Commands options, PGREP, PRSTAT, CDE Process Manager, Scheduling Process, Scheduling Priorities, Changing the Priority of a time-sharing process, Killing Process.' },
            { unit: 5, title: 'System Security', content: 'Physical Security, Controlling System Access, Restricted Shells, Controlling File Access, File Access Commands, Access Control List (ACLs), Setting, Modifying and Deleting ACL Entries on a file, Restricting FTP, Securing Super User Access, Restricting Root Access, Monitoring super user Access, TCP Wrappers.' },
            { unit: 6, title: 'Dynamic Host Configuration Protocol (DHCP)', content: 'Introduction, DHCP Leased Time, DHCP Scopes, DHCP IP Address Allocation Types, Planning DHCP Deployment, DHCP Configuration files, Automatic Startup of DHCP Server, Configuration of DHCP Clients, Manually Configuring the DHCP.' },
          ] },
          { id: 'cs506',  name: 'CS-506 - Lab (Python)',                                                                  units: [] },
          { id: 'cs507',  name: 'CS-507 - Evaluation of Internship-II',                                                   units: [] },
          { id: 'cs508',  name: 'CS-508 - Minor Project-I',                                                               units: [] },
        ],
      },
      6: {
        label: 'Semester 6',
        subjects: [
          { id: 'cs601',  name: 'CS-601 - Machine Learning', units: [
            { unit: 1, title: 'Introduction to Machine Learning', content: 'Introduction to machine learning, scope and limitations, regression, probability, statistics and linear algebra for machine learning, convex optimization, data visualization, hypothesis function and testing, data distributions, data preprocessing, data augmentation, normalizing data sets, machine learning models, supervised and unsupervised learning.' },
            { unit: 2, title: 'Neural Networks & Backpropagation', content: 'Linearity vs non-linearity, activation functions (sigmoid, ReLU, etc.), weights and bias, loss function, gradient descent, multilayer network, backpropagation, weight initialization, training, testing, unstable gradient problem, auto encoders, batch normalization, dropout, L1 and L2 regularization, momentum, tuning hyper parameters.' },
            { unit: 3, title: 'Convolutional Neural Networks', content: 'CNN: flattening, subsampling, padding, stride, convolution layer, pooling layer, loss layer, dense layer, 1x1 convolution, inception network, input channels, transfer learning, one shot learning, dimension reductions, implementation of CNN (TensorFlow, Keras, etc.).' },
            { unit: 4, title: 'Recurrent Networks & Reinforcement Learning', content: 'Recurrent neural network, Long short-term memory, gated recurrent unit, translation, beam search and width, Bleu score, attention model. Reinforcement Learning: RL-framework, MDP, Bellman equations, Value Iteration and Policy Iteration, Actor-critic model, Q-learning, SARSA.' },
            { unit: 5, title: 'SVM, Bayesian Learning & Applications', content: 'Support Vector Machines, Bayesian learning, application of machine learning in computer vision, speech processing, natural language processing etc. Case Study: ImageNet Competition.' },
          ] },
          { id: 'cs602',  name: 'CS-602 - Computer Networks', units: [
            { unit: 1, title: 'Computer Network Basics & Physical Layer', content: 'Definitions, goals, components, Architecture, Classifications & Types. Layered Architecture: Protocol hierarchy, Design Issues, Interfaces and Services, Connection Oriented & Connectionless Services, Service primitives. ISO-OSI Reference Model: Principle, Model, Descriptions of various layers and comparison with TCP/IP. Principles of physical layer: Media, Bandwidth, Data rate and Modulations.' },
            { unit: 2, title: 'Data Link Layer', content: 'Need, Services Provided, Framing, Flow Control, Error control. Data Link Layer Protocols: Elementary & Sliding Window protocols (1-bit, Go-Back-N, Selective Repeat, Hybrid ARQ). Protocol verification: Finite State Machine Models & Petri net models. ARP/RARP/GARP.' },
            { unit: 3, title: 'MAC Sub Layer', content: 'MAC Addressing, Binary Exponential Back-off (BEB) Algorithm, Distributed Random Access Schemes: for Data Services (ALOHA and Slotted ALOHA), for LANs (CSMA, CSMA/CD, CSMA/CA). Collision Free Protocols: Basic Bit Map, BRAP, Binary Count Down, MLMA. Limited Contention Protocols: Adaptive Tree Walk, Performance Metrics. IEEE Standards 802 series and variants.' },
            { unit: 4, title: 'Network Layer', content: 'Need, Services Provided, Design issues. Routing algorithms: Least Cost Routing, Dijkstra algorithm, Bellman-ford algorithm, Hierarchical Routing, Broadcast Routing, Multicast Routing. IP Addresses, Header format, Packet forwarding, Fragmentation and reassembly, ICMP, Comparative study of IPv4 & IPv6.' },
            { unit: 5, title: 'Transport & Application Layer', content: 'Transport Layer: Design Issues, UDP: Header Format, Per-Segment Checksum, Real-Time Traffic. TCP: Connection Management, Reliability, TCP Flow Control, TCP Congestion Control, TCP Header Format, TCP Timer Management. Application Layer: WWW and HTTP, FTP, SSH, Email (SMTP, MIME, IMAP), DNS, Network Management (SNMP).' },
          ] },
          // CS-603 Electives — student chooses one
          { id: 'cs603a', name: 'CS-603 - Advanced Computer Architecture', isElective: true, electiveGroup: 'CS-603', units: [
            { unit: 1, title: 'Parallel Computer Models & Interconnection', content: 'Flynn Classification, System Attributes to Performance, Parallel computer models: Multiprocessors and multicomputers, Multivector and SIMD Computers. Data and resource dependences, Hardware and software parallelism, Program partitioning and scheduling, Grain size and latency, Control flow, data flow and Demand driven mechanisms. Static and Dynamic interconnection networks: Bus Systems, Crossbar Switch, Multiport Memory, Multistage and Combining Networks.' },
            { unit: 2, title: 'Instruction Set Architecture & Memory Hierarchy', content: 'Instruction set architecture, CISC Scalar Processors, RISC Scalar Processors, VLIW architecture, Memory Hierarchy, Inclusion, Coherence and Locality, Memory capacity planning. Interleaved memory organization, pipelined memory access, Bandwidth and Fault Tolerance. Backplane Bus System: specification, Addressing and timing protocols, Arbitration, transaction and interrupt.' },
            { unit: 3, title: 'Pipeline Design & Superscalar Processing', content: 'Linear pipeline processor, Nonlinear pipeline processor, Instruction pipeline design, Mechanisms for instruction pipelining, pipeline hazards, Dynamic instruction scheduling (scoreboarding and Tomasulo algorithm), Branch handling techniques, Arithmetic Pipeline Design, Static and Multifunctional arithmetic pipelines. Superscalar pipeline design, Super pipeline processor design.' },
            { unit: 4, title: 'Cache Coherence, Vector & Multithreading', content: 'Cache coherence, Snoopy protocols, Directory based protocols. Message routing schemes in multicomputer network, deadlock and virtual channel. Vector Processing Principles, Vector instruction types, Vector-access memory schemes. Vector supercomputer architecture, SIMD organization. Principles of Multithreading: Issues, Solutions and Multiple-Context Processors.' },
            { unit: 5, title: 'Parallel Programming Models & Environments', content: 'Parallel Programming Models: Shared-Variable Model, Message-Passing Model, Data-Parallel Model, Object-Oriented Model, Functional and Logic Models. Parallel Languages and Compilers, Language Features for Parallelism, Parallel Programming Environment, Software Tools and Environments.' },
          ] },
          { id: 'cs603b', name: 'CS-603 - Computer Graphics & Visualisation', isElective: true, electiveGroup: 'CS-603', units: [
            { unit: 1, title: 'Raster Graphics & Scan Conversion', content: 'Introduction to Raster Scan displays, Pixels, Frame buffer, Vector & Character generation, Random Scan systems, Display devices. Scan Conversion: Line Drawing algorithms (simple DDA, Bresenham), Circle Drawing Algorithms (Midpoint, Bresenham), Polygon fill algorithms (Boundary-fill, Flood-fill).' },
            { unit: 2, title: '2-D Transformations & Windowing', content: '2-D Transformation: Translation, Rotation, Scaling, Shearing, Reflection. Inverse Transformation, Homogeneous coordinate system, Matrices Transformation, Composite Transformation. Windowing & Clipping: World Coordinate System, Screen Coordinate System, Viewing Transformation, Line Clipping and Polygon Clipping Algorithms.' },
            { unit: 3, title: '3-D Transformations, Projections & Rendering', content: '3-D Transformations: Translation, Rotation and Scaling. Parallel & Perspective Projection: types, Hidden Surface elimination (Depth comparison, Back face detection, Painter Algorithm, Z-Buffer). Curve generation, Bezier and B-spline methods. Basic Illumination Model: Diffuse reflection, Specular reflection, Phong Shading, Gouraud shading, Ray Tracing, Color models: RGB, YIQ, CMY, HSV.' },
            { unit: 4, title: 'Visualization', content: 'Visualization of 2D/3D scalar fields: color mapping, ISO surfaces. Direct volume data rendering: ray-casting, transfer functions, segmentation. Visualization of Vector fields and flow data, Time-varying data, High-dimensional data: dimension reduction, parallel coordinates, Non-spatial data: multi-variate, tree/graph structured, text. Perceptual and cognitive foundations, Evaluation of visualization methods, Basic Animation Techniques.' },
            { unit: 5, title: 'Multimedia', content: 'Basics of multimedia, applications, Text types, Unicode Standard, text Compression, Text file formats. Audio: Digital Audio, processing, sound cards, file formats. Video: color spaces, Digital Video, processing, file formats. Animation: Uses, Principles, Computer based animation, 3D Animation, file formats, Special Effects, Storyboarding. Compression: Lossless/Lossy, Image/Audio/Video Compression, MPEG Standards, Multimedia databases.' },
          ] },
          { id: 'cs603c', name: 'CS-603 - Compiler Design', isElective: true, electiveGroup: 'CS-603', units: [
            { unit: 1, title: 'Introduction & Lexical Analysis', content: 'Introduction to Compiler, Major data structures in compiler, types of Compiler, Front-end and Back-end, Compiler structure: analysis-synthesis model, various phases of a compiler. Lexical analysis: Input buffering, Specification & Recognition of Tokens, Design of a Lexical Analyzer Generator, LEX.' },
            { unit: 2, title: 'Syntax Analysis & Syntax Directed Translation', content: 'Syntax analysis: CFGs, Top-down parsing (Brute force, recursive descent, predictive parsing), bottom-up parsing (operator precedence, LR parsers: SLR, LALR, LR), Parser generation. Syntax directed definitions: Construction of Syntax trees, Bottom-up evaluation of S-attributed definition, L-attribute definition, Top-down translation, Bottom-up evaluation of inherited attributes.' },
            { unit: 3, title: 'Type Checking & Run Time Environment', content: 'Type checking: type system, specification of simple type checker, equivalence of expression types, type conversion, overloading of functions and operations, polymorphic functions. Run time Environment: storage organization, Storage allocation strategies, parameter passing, dynamic storage allocation, Symbol table, Error Detection & Recovery, Ad-Hoc and Systematic Methods.' },
            { unit: 4, title: 'Code Generation', content: 'Intermediate code generation: Declarations, Assignment statements, Boolean expressions, Case statements, Back patching, Procedure calls. Code Generation: Issues in design of code generator, Basic block and flow graphs, Register allocation and assignment, DAG representation of basic blocks, peephole optimization, generating code from DAG.' },
            { unit: 5, title: 'Code Optimization', content: 'Introduction to Code optimization: sources of optimization of basic blocks, loops in flow graphs, dead code elimination, loop optimization, Introduction to global data flow analysis, Code Improving transformations, Data flow analysis of structure flow graph, Symbolic debugging of optimized code.' },
          ] },
          // CS-604 Electives — student chooses one
          { id: 'cs604a', name: 'CS-604 - Knowledge Management', isElective: true, electiveGroup: 'CS-604', units: [
            { unit: 1, title: 'Introduction to Knowledge Management', content: 'Introduction to Knowledge Management: foundations including cultural issues, technology applications, organizational concepts and processes, management aspects, and decision support systems. The Evolution of Knowledge Management: From Information Management to KM, Key Challenges, Ethics for Knowledge Management.' },
            { unit: 2, title: 'Creating the Culture of Learning & Knowledge Sharing', content: 'Organization and Knowledge Management: Building the Learning Organization. Knowledge Markets: Cooperation among Distributed Technical Specialists, Tacit Knowledge and Quality Assurance.' },
            { unit: 3, title: 'Knowledge Management Tools', content: 'Telecommunications and Networks in KM, Internet Search Engines and KM, Information Technology in Support of KM, KM and Vocabulary Control, Information Mapping in Information Retrieval, Information Coding in the Internet Environment, Repackaging Information.' },
            { unit: 4, title: 'Knowledge Management Applications', content: 'Components of a Knowledge Strategy, Case Studies: From Library to Knowledge Center, Knowledge Management in the Health Sciences, Knowledge Management in Developing Countries.' },
            { unit: 5, title: 'Future Trends & Case Studies', content: 'Advanced topics and case studies in knowledge management, Development of a knowledge management map/plan integrated with an organization strategic and business plan, Case study on Corporate Memories for supporting process life-cycles.' },
          ] },
          { id: 'cs604b', name: 'CS-604 - Project Management', isElective: true, electiveGroup: 'CS-604', units: [
            { unit: 1, title: 'Conventional Software Management', content: 'Evolution of software economics. Improving software economics: reducing product size, software processes, team effectiveness, automation through software environments. Principles of modern software management.' },
            { unit: 2, title: 'Software Management Process Framework', content: 'Life cycle phases: inception, elaboration, construction and training phase. Artifacts of the process: management artifacts, engineering artifacts, pragmatics artifacts. Model based software architectures, Workflows of the process, Checkpoints of the process.' },
            { unit: 3, title: 'Software Management Disciplines', content: 'Iterative process planning. Project organisations and responsibilities. Process automation. Project control and process instrumentation: core metrics, management indicators, life cycle expectations. Process discriminants.' },
            { unit: 4, title: 'Project Planning & Risk Management', content: 'Feasibility Analysis, Project and Process Planning, Resource Allocation, Software Effort, Schedule and Cost estimations, Project Scheduling and Tracking, Risk Assessment and Mitigation.' },
            { unit: 5, title: 'Quality & Metrics', content: 'Software Quality Assurance (SQA), Project Plan, Project Metrics, Process Metrics, Quality Standards and Reviews.' },
          ] },
          { id: 'cs604c', name: 'CS-604 - Rural Technology & Community Development', isElective: true, electiveGroup: 'CS-604', units: [
            { unit: 1, title: 'Rural Management', content: 'Principles and Practices: Introduction to Management and Theory of Management, Planning, Organisation Structure and Design, Motivation and Leadership, Management Control and Managerial Decision Making.' },
            { unit: 2, title: 'Human Resource Management for Rural India', content: 'Nature and Scope of HRM, Human Resource Planning, Recruitment and Selection, Training and Development, Performance Appraisal, Welfare programme and Fringe benefits, Wage and Salary Administration, Morale and Productivity, Industrial Relations and Industrial Disputes.' },
            { unit: 3, title: 'Management of Rural Financing', content: 'Rural Credit System, Role of Rural Credit in Rural Development, Evolution and Growth of Rural Credit System in India. Agricultural Credit, Agricultural Credit Review Committee, Problems and Prospects. Rural Credit to Non-farm Sector, Role of Government and Non-Government Institutions, Growth and Present trend of Rural Financing towards Small scale and Cottage Industries.' },
            { unit: 4, title: 'Research Methodology – I', content: 'Concept of Social Research, Traditional Research, Action Research and Participatory Research. Qualitative Data Construction and Methods of Data Collection, Techniques of Interview. Qualitative methods: Sociometry, Case Studies, observation, coding and content analysis.' },
            { unit: 5, title: 'Research Methodology – II', content: 'Collection, Tabulation and Presentation of data. Measures of Central Tendency, Dispersion, Moments, Skewness and Kurtosis, Correlation and Regression. Sampling Theory and Test of Significance.' },
          ] },
        ],
      },
    },
  },

  // ══════════════════════════════════════════════
  //  FOURTH YEAR (Sem 7 & 8)
  // ══════════════════════════════════════════════
  'fourth-year': {
    label: 'Fourth Year',
    semesters: {
      7: {
        label: 'Semester 7',
        subjects: [
          { id: 'cs701',  name: 'CS-701 - Software Architectures',                                                        units: [] },
          // CS-702 Departmental Electives — student chooses one
          { id: 'cs702a', name: 'CS-702(A) - Computational Intelligence',                                                 units: [], isElective: true, electiveGroup: 'CS-702 Departmental' },
          { id: 'cs702b', name: 'CS-702(B) - Deep & Reinforcement Learning',                                              units: [], isElective: true, electiveGroup: 'CS-702 Departmental' },
          { id: 'cs702c', name: 'CS-702(C) - Wireless & Mobile Computing',                                                units: [], isElective: true, electiveGroup: 'CS-702 Departmental' },
          { id: 'cs702d', name: 'CS-702(D) - Big Data',                                                                   units: [], isElective: true, electiveGroup: 'CS-702 Departmental' },
          // CS-703 Open Electives — student chooses one
          { id: 'cs703a', name: 'CS-703(A) - Cryptography & Information Security',                                        units: [], isElective: true, electiveGroup: 'CS-703 Open' },
          { id: 'cs703b', name: 'CS-703(B) - Data Mining and Warehousing',                                                units: [], isElective: true, electiveGroup: 'CS-703 Open' },
          { id: 'cs703c', name: 'CS-703(C) - Agile Software Development',                                                 units: [], isElective: true, electiveGroup: 'CS-703 Open' },
          { id: 'cs703d', name: 'CS-703(D) - Disaster Management',                                                        units: [], isElective: true, electiveGroup: 'CS-703 Open' },
          { id: 'cs7sem', name: 'Seminar / Internship / Project Work',                                                    units: [] },
        ],
      },
      8: {
        label: 'Semester 8',
        subjects: [
          { id: 'cs801',  name: 'CS-801 - Internet of Things (IoT)',                                                      units: [] },
          // CS-802 Departmental Electives — student chooses one
          { id: 'cs802a', name: 'CS-802(A) - Blockchain Technologies',                                                    units: [], isElective: true, electiveGroup: 'CS-802 Departmental' },
          { id: 'cs802b', name: 'CS-802(B) - Cloud Computing',                                                            units: [], isElective: true, electiveGroup: 'CS-802 Departmental' },
          { id: 'cs802c', name: 'CS-802(C) - High Performance Computing',                                                 units: [], isElective: true, electiveGroup: 'CS-802 Departmental' },
          { id: 'cs802d', name: 'CS-802(D) - Object-Oriented Software Engineering',                                       units: [], isElective: true, electiveGroup: 'CS-802 Departmental' },
          // CS-803 Open Electives — student chooses one
          { id: 'cs803a', name: 'CS-803(A) - Image Processing & Computer Vision',                                         units: [], isElective: true, electiveGroup: 'CS-803 Open' },
          { id: 'cs803b', name: 'CS-803(B) - Cyber Security',                                                             units: [], isElective: true, electiveGroup: 'CS-803 Open' },
          { id: 'cs803c', name: 'CS-803(C) - Internet of Things (IoT)',                                                   units: [], isElective: true, electiveGroup: 'CS-803 Open' },
          { id: 'cs8proj', name: 'Major Project / Dissertation / Viva-Voce',                                              units: [] },
          { id: 'cs8int',  name: 'Internship (as per college requirements)',                                               units: [] },
        ],
      },
    },
  },
}
